export const ADD_PRODUCT = "CART_ADD_PRODUCT";
export type ADD_PRODUCT = typeof ADD_PRODUCT;

export const REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";
export type REMOVE_PRODUCT = typeof REMOVE_PRODUCT;

export const CLEAR = "CART_CLEAR";
export type CLEAR = typeof CLEAR;

export const CREATE_ORDER_SUCCESS = "CART_CREATE_ORDER_SUCCESS";
export type CREATE_ORDER_SUCCESS = typeof CREATE_ORDER_SUCCESS;
