export const HOME_FETCH_CLIENT_INFO = "HOME_FETCH_CLIENT_INFO";
export type HOME_FETCH_CLIENT_INFO = typeof HOME_FETCH_CLIENT_INFO;

export const HOME_SET_VALUE = "HOME_SET_VALUE";
export type HOME_SET_VALUE = typeof HOME_SET_VALUE;

export const HOME_SET_CHANGE_PWD_SUCCESS = "HOME_SET_CHANGE_PWD_SUCCESS";
export type HOME_SET_CHANGE_PWD_SUCCESS = typeof HOME_SET_CHANGE_PWD_SUCCESS;

export const HOME_SET_UPDATE_INFO_SUCCESS = "HOME_SET_UPDATE_INFO_SUCCESS";
export type HOME_SET_UPDATE_INFO_SUCCESS = typeof HOME_SET_UPDATE_INFO_SUCCESS;
