export const REGISTRATION_SET_VALUE = "REGISTRATION_SET_VALUE";
export type REGISTRATION_SET_VALUE = typeof REGISTRATION_SET_VALUE;

export const REGISTRATION_FETCH = "REGISTRATION_FETCH";
export type REGISTRATION_FETCH = typeof REGISTRATION_FETCH;