export const REGISTRATION_SET_VALUE = "REGISTRATION_SET_VALUE";
export type REGISTRATION_SET_VALUE = typeof REGISTRATION_SET_VALUE;

export const REGISTRATION_FETCH = "REGISTRATION_FETCH";
export type REGISTRATION_FETCH = typeof REGISTRATION_FETCH;

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export type REGISTRATION_SUCCESS = typeof REGISTRATION_SUCCESS;
